name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests with coverage
      run: mvn -B test

    - name: Upload coverage to Qlty
      uses: qltysh/qlty-action/coverage@v2
      with:
        oidc: true
        files: target/site/jacoco/jacoco.xml
        add-prefix: src/main/java/
